<a href="https://colab.research.google.com/github/RiRa25/Loan-Prediction-System/blob/main/OEA_DesicionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('/content/outputfinal (1).csv')
data.head()

income_annum   loan_amount   loan_term   cibil_score   loan_status
0        9600000      29900000          12           778             1
1        4100000      12200000           8           417             0
2        9100000      29700000          20           506             0
3        8200000      30700000           8           467             0
4        9800000      24200000          20           382             0

In [3]:
X = data.iloc[:, 0:4]
Y = data.iloc[:, 4]
print(X)
print(Y)

       income_annum   loan_amount   loan_term   cibil_score
0           9600000      29900000          12           778
1           4100000      12200000           8           417
2           9100000      29700000          20           506
3           8200000      30700000           8           467
4           9800000      24200000          20           382
...             ...           ...         ...           ...
4264        1000000       2300000          12           317
4265        3300000      11300000          20           559
4266        6500000      23900000          18           457
4267        4100000      12800000           8           780
4268        9200000      29700000          10           607

[4269 rows x 4 columns]
0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name:  loan_status, Length: 4269, dtype: int64


In [4]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.3, random_state=1)

In [5]:
print(Ytrain)

1398    1
1519    0
4192    1
434     1
925     0
       ..
2895    1
2763    1
905     0
3980    1
235     1
Name:  loan_status, Length: 2988, dtype: int64


In [6]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
Xtrain = sc_X.fit_transform(Xtrain)
Xtest = sc_X.fit_transform(Xtest)
print(Xtrain)
print(Xtest)

[[ 1.55378947  2.41719228  1.57665864  1.67833654]
 [ 1.02113499  0.72307099  0.88114583 -0.61293642]
 [-0.64784903 -0.76066922 -0.16212338  0.39313013]
 ...
 [ 1.66032036  2.43933766  0.53338943 -0.83392214]
 [-1.64213738 -1.55790276 -0.50987979  1.31196549]
 [ 0.66603201  0.93345207 -1.2053926  -0.70598304]]
[[ 1.53102472  2.40540596  0.56608215 -1.21845854]
 [ 1.42320292  0.30748629  0.56608215 -0.78575098]
 [ 0.63250969  0.32956966 -0.86067876 -1.35115552]
 ...
 [-0.05036173 -0.09001428  0.20939192  1.40086454]
 [-1.48798578 -1.3377244   1.2794626  -0.09341889]
 [ 1.31538111  1.62144651  1.2794626   1.74703058]]


In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(Xtrain, Ytrain)

In [8]:
Ypred = classifier.predict(Xtest)
print(Ypred)

[0 0 0 ... 1 1 1]


In [9]:
from sklearn import metrics
print('Accuracy Score: ', metrics.accuracy_score(Ytest, Ypred))

Accuracy Score:  0.9578454332552693


In [10]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Ytest, Ypred)
print(confusion_matrix)

[[448  35]
 [ 19 779]]


In [11]:
from sklearn.metrics import classification_report
print(classification_report(Ytest, Ypred))

              precision    recall  f1-score   support

           0       0.96      0.93      0.94       483
           1       0.96      0.98      0.97       798

    accuracy                           0.96      1281
   macro avg       0.96      0.95      0.95      1281
weighted avg       0.96      0.96      0.96      1281

